import Head from "next/head";
import { useMoralis } from "react-moralis";
import Loading from "../components/Loading";
import Login from "../components/Login";

export default function Home() {
  const { isAuthenticated, isInitializing, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;

  if (isInitializing) return <Loading />;

  return (
    <div className="h-screen">
      <Head>
        <title>BorderLands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to the borderlands</h1>
      <button onClick={logout}>Logout</button>
    </div>
  );
}
